configName: pic32mz_w1_curiosity
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MZ1025W104132
projectName: ''
settings:
  PackageFilter: audio;bootloader;bsp;core;core_apps_pic32cz_ca;core_apps_sam_d21_da1;crypto;cryptoauthlib;csp;gfx;mbed_os_rtos;mbed_os_rtos_apps;micrium_ucos3;motor_control;net;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.4.193\atdf\PIC32MZ1025W104132.atdf
