package:
  format-version: "1.0.0"
  name: "core_apps_pic32mz_w1"
  version: "v3.5.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.21.1"
    - name: "usb"
      type: "package"
      version: "v3.14.0"
    - name: "FreeRTOS-Kernel"
      type: "package"
      version: "V11.1.0"
    - name: "littlefs"
      type: "package"
      version: "v2.9.3"
    - name: "core"
      type: "package"
      version: "v3.14.0"
