files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 436FA3197E9DC5B765726AF9D212B505
  logicalPath: config\pic32mz_w1_curiosity\bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 436FA3197E9DC5B765726AF9D212B505
- generatedChecksum: 4238740A6A08738E296E6139E26E53D8
  logicalPath: config\pic32mz_w1_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4238740A6A08738E296E6139E26E53D8
- generatedChecksum: BC7A48079909D7E2B6EB5C5B1BE554C4
  logicalPath: config\pic32mz_w1_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: BC7A48079909D7E2B6EB5C5B1BE554C4
- generatedChecksum: D7770AD18B9875272CF95E8BF2D230E9
  logicalPath: config\pic32mz_w1_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D7770AD18B9875272CF95E8BF2D230E9
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D97FAAECFD6664972F98D9221C891BE7
  logicalPath: config\pic32mz_w1_curiosity\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: D97FAAECFD6664972F98D9221C891BE7
- generatedChecksum: 86BFDF57675E4C252A9F37EF4B0570A9
  logicalPath: config\pic32mz_w1_curiosity\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 86BFDF57675E4C252A9F37EF4B0570A9
- generatedChecksum: 98AB2CEE4F371667A7FC6D08AD7BC186
  logicalPath: config\pic32mz_w1_curiosity\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 98AB2CEE4F371667A7FC6D08AD7BC186
- generatedChecksum: 7FD2233814045570A93C1D58A8069F0B
  logicalPath: config\pic32mz_w1_curiosity\peripheral\uart
  name: plib_uart1.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7FD2233814045570A93C1D58A8069F0B
- generatedChecksum: 20C22A19D5DC74DEBFC4CCCA83B6F603
  logicalPath: config\pic32mz_w1_curiosity\system\console
  name: sys_console.c
  physicalPath: system\console\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 20C22A19D5DC74DEBFC4CCCA83B6F603
- generatedChecksum: 5BA0902794A8669B3FE37E8A8BEE9D65
  logicalPath: config\pic32mz_w1_curiosity\system\console
  name: sys_console_local.h
  physicalPath: system\console\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5BA0902794A8669B3FE37E8A8BEE9D65
- generatedChecksum: CA5E9B63704372DE5FBC0BDC006B16C3
  logicalPath: config\pic32mz_w1_curiosity\system\console
  name: sys_console_uart.c
  physicalPath: system\console\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA5E9B63704372DE5FBC0BDC006B16C3
- generatedChecksum: 767495C6A39617A915D8107093DC1A72
  logicalPath: config\pic32mz_w1_curiosity\system\console
  name: sys_console_uart.h
  physicalPath: system\console\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 767495C6A39617A915D8107093DC1A72
- generatedChecksum: 5D10B9438117B64220180660AB022150
  logicalPath: config\pic32mz_w1_curiosity\system\console
  name: sys_console_uart_definitions.h
  physicalPath: system\console\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5D10B9438117B64220180660AB022150
- generatedChecksum: 68C0D499B9EDAA3BFD7E131A48514212
  logicalPath: config\pic32mz_w1_curiosity\system\debug
  name: sys_debug.c
  physicalPath: system\debug\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 68C0D499B9EDAA3BFD7E131A48514212
- generatedChecksum: B8C6C7356AC7841AECC7C779040F745C
  logicalPath: config\pic32mz_w1_curiosity\system\debug
  name: sys_debug_local.h
  physicalPath: system\debug\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: B8C6C7356AC7841AECC7C779040F745C
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config\pic32mz_w1_curiosity\system\int
  name: sys_int.c
  physicalPath: system\int\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 9A49A2339A0774ACCBC2178A9EE76586
  logicalPath: config\pic32mz_w1_curiosity
  name: system_pmu_mldo_trim.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9A49A2339A0774ACCBC2178A9EE76586
- generatedChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
  logicalPath: config\pic32mz_w1_curiosity
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mz_w1_curiosity\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: D4C6E928D289C9C949F1D14FE0887451
  logicalPath: config\pic32mz_w1_curiosity\bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: D4C6E928D289C9C949F1D14FE0887451
- generatedChecksum: 4855B5EA5BE394CEACBC41B6FEAD2183
  logicalPath: config\pic32mz_w1_curiosity
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4855B5EA5BE394CEACBC41B6FEAD2183
- generatedChecksum: F09A933183FEA9AE9A77A59AD2DAA1C0
  logicalPath: config\pic32mz_w1_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F09A933183FEA9AE9A77A59AD2DAA1C0
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mz_w1_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config\pic32mz_w1_curiosity\driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config\pic32mz_w1_curiosity\driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mz_w1_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config\pic32mz_w1_curiosity\osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config\pic32mz_w1_curiosity\osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config\pic32mz_w1_curiosity\osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 9238A3759A2C6748FE493370DE35B5E0
  logicalPath: config\pic32mz_w1_curiosity\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 9238A3759A2C6748FE493370DE35B5E0
- generatedChecksum: 2B5072810107E051495C4B6379DEDA4E
  logicalPath: config\pic32mz_w1_curiosity\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 2B5072810107E051495C4B6379DEDA4E
- generatedChecksum: 3C52CEA231878411E3950ADD556AF20C
  logicalPath: config\pic32mz_w1_curiosity\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C52CEA231878411E3950ADD556AF20C
- generatedChecksum: D5B124F7B292B92BE6CA0A7BDFD6F62F
  logicalPath: config\pic32mz_w1_curiosity\peripheral\uart
  name: plib_uart1.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: D5B124F7B292B92BE6CA0A7BDFD6F62F
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config\pic32mz_w1_curiosity\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 0525B31317EA9CBFEC119F7C1B8987DA
  logicalPath: config\pic32mz_w1_curiosity\system\console
  name: sys_console.h
  physicalPath: system\console
  security: NON_SECURE
  type: HEADER
  userChecksum: 0525B31317EA9CBFEC119F7C1B8987DA
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config\pic32mz_w1_curiosity\system\debug
  name: sys_debug.h
  physicalPath: system\debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config\pic32mz_w1_curiosity\system\int
  name: sys_int.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config\pic32mz_w1_curiosity\system\int
  name: sys_int_mapping.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config\pic32mz_w1_curiosity\system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config\pic32mz_w1_curiosity\system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config\pic32mz_w1_curiosity\system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\pic32mz_w1_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config\pic32mz_w1_curiosity
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 79557AEFF1105797385F9C4EE40A5C4F
  logicalPath: config\pic32mz_w1_curiosity
  name: p32MZ1025W104132.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 79557AEFF1105797385F9C4EE40A5C4F
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;../src/packs/PIC32MZ1025W104132_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;../src/packs/PIC32MZ1025W104132_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
