files:
- generatedChecksum: F58DB2348A0FCE945652B285010E5F8A
  logicalPath: FreeRTOS\Source
  name: FreeRTOS_tasks.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: F58DB2348A0FCE945652B285010E5F8A
- generatedChecksum: 436FA3197E9DC5B765726AF9D212B505
  logicalPath: config\pic32mz_w1_curiosity\bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 436FA3197E9DC5B765726AF9D212B505
- generatedChecksum: 8ACE0DEBD82F6829438A4674565451FB
  logicalPath: FreeRTOS\Source
  name: croutine.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8ACE0DEBD82F6829438A4674565451FB
- generatedChecksum: B3B5445B14BD9B6A35F1C5B995C9BBF7
  logicalPath: FreeRTOS\Source
  name: event_groups.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: B3B5445B14BD9B6A35F1C5B995C9BBF7
- generatedChecksum: 4238740A6A08738E296E6139E26E53D8
  logicalPath: config\pic32mz_w1_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4238740A6A08738E296E6139E26E53D8
- generatedChecksum: B7DBFD6F500AAD4713403E985EB18EAE
  logicalPath: config\pic32mz_w1_curiosity
  name: freertos_hooks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B7DBFD6F500AAD4713403E985EB18EAE
- generatedChecksum: 972E955D94A63BA89BF6ABD6AADB1023
  logicalPath: FreeRTOS\Source\portable\MemMang
  name: heap_1.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\portable\MemMang
  security: NON_SECURE
  type: SOURCE
  userChecksum: 972E955D94A63BA89BF6ABD6AADB1023
- generatedChecksum: EE38CA39BBAD110F37D7DB3EF5362A6C
  logicalPath: config\pic32mz_w1_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EE38CA39BBAD110F37D7DB3EF5362A6C
- generatedChecksum: 89C2526AFD3A6ADDA278834BB327E2CE
  logicalPath: config\pic32mz_w1_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 89C2526AFD3A6ADDA278834BB327E2CE
- generatedChecksum: B1FB078472FCF55DEF000C9CD0525B33
  logicalPath: config\pic32mz_w1_curiosity
  name: interrupts_a.S
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B1FB078472FCF55DEF000C9CD0525B33
- generatedChecksum: 3FEE521CEF14928AE38E7FA9BF6D75E6
  logicalPath: FreeRTOS\Source
  name: list.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3FEE521CEF14928AE38E7FA9BF6D75E6
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 8FDD6248506F28B32C4F5FD9AA0D9C6F
  logicalPath: config\pic32mz_w1_curiosity\osal
  name: osal_freertos.c
  physicalPath: osal
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8FDD6248506F28B32C4F5FD9AA0D9C6F
- generatedChecksum: BBBAECCF765D38C545EC10624BFBFE24
  logicalPath: config\pic32mz_w1_curiosity\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: BBBAECCF765D38C545EC10624BFBFE24
- generatedChecksum: 2B3DC6F942546ADD8BD498BDACCD4A7C
  logicalPath: config\pic32mz_w1_curiosity\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2B3DC6F942546ADD8BD498BDACCD4A7C
- generatedChecksum: 20D6F09D11F7E98E578CC91F18959C39
  logicalPath: config\pic32mz_w1_curiosity\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 20D6F09D11F7E98E578CC91F18959C39
- generatedChecksum: 8C0EFED101CB83560D7FF9C3AE07832B
  logicalPath: config\pic32mz_w1_curiosity\peripheral\uart
  name: plib_uart1.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8C0EFED101CB83560D7FF9C3AE07832B
- generatedChecksum: C887913E7F045D65EF8FA7362D0DFDD8
  logicalPath: FreeRTOS\Source\portable\MPLAB\PIC32MZ
  name: port.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\portable\MPLAB\PIC32MZ
  security: NON_SECURE
  type: SOURCE
  userChecksum: C887913E7F045D65EF8FA7362D0DFDD8
- generatedChecksum: 17FB1DE2D7DF3950AACC03B19F54459C
  logicalPath: FreeRTOS\Source\portable\MPLAB\PIC32MZ
  name: port_asm.S
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\portable\MPLAB\PIC32MZ
  security: NON_SECURE
  type: SOURCE
  userChecksum: 17FB1DE2D7DF3950AACC03B19F54459C
- generatedChecksum: 09041728D74A4E3A32C7D4EAA96C4EE7
  logicalPath: FreeRTOS\Source
  name: queue.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 09041728D74A4E3A32C7D4EAA96C4EE7
- generatedChecksum: D6CF30BDCE1A813D9ACF3905EBD6A871
  logicalPath: FreeRTOS\Source
  name: stream_buffer.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: D6CF30BDCE1A813D9ACF3905EBD6A871
- generatedChecksum: 9A49A2339A0774ACCBC2178A9EE76586
  logicalPath: config\pic32mz_w1_curiosity
  name: system_pmu_mldo_trim.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9A49A2339A0774ACCBC2178A9EE76586
- generatedChecksum: null
  logicalPath: ''
  name: task1.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task2.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task3.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task4.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 923B2290DA9C0164D4F2DE731494E321
  logicalPath: config\pic32mz_w1_curiosity
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 923B2290DA9C0164D4F2DE731494E321
- generatedChecksum: F1B86F6E1527FD59A8713B67564F2898
  logicalPath: FreeRTOS\Source
  name: timers.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: F1B86F6E1527FD59A8713B67564F2898
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mz_w1_curiosity\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: AF3A8D8AA610E7DFD3E38DDAC5E42074
  logicalPath: FreeRTOS\Source\include
  name: FreeRTOS.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: AF3A8D8AA610E7DFD3E38DDAC5E42074
- generatedChecksum: 2475A597674F39D9AB9F2D8D2033D1F0
  logicalPath: config\pic32mz_w1_curiosity
  name: FreeRTOSConfig.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2475A597674F39D9AB9F2D8D2033D1F0
- generatedChecksum: 774011E09B9B257B4F572704E6AB9713
  logicalPath: FreeRTOS\Source\portable\MPLAB\PIC32MZ
  name: ISR_Support.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\portable\MPLAB\PIC32MZ
  security: NON_SECURE
  type: HEADER
  userChecksum: 774011E09B9B257B4F572704E6AB9713
- generatedChecksum: 1A6D4F7FF5A67D407A3E5731986EBC3D
  logicalPath: config\pic32mz_w1_curiosity\bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 1A6D4F7FF5A67D407A3E5731986EBC3D
- generatedChecksum: 76016C9804D6DE17B74C92D82294562E
  logicalPath: config\pic32mz_w1_curiosity
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 76016C9804D6DE17B74C92D82294562E
- generatedChecksum: 48B661D8C967C6BC397001F10FB43D1D
  logicalPath: FreeRTOS\Source\include
  name: croutine.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 48B661D8C967C6BC397001F10FB43D1D
- generatedChecksum: F0BBFDBFBDE5D5ACF5255832D0C5799F
  logicalPath: config\pic32mz_w1_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F0BBFDBFBDE5D5ACF5255832D0C5799F
- generatedChecksum: 1EA4EDD5EA90F43EC407DE32441159A9
  logicalPath: FreeRTOS\Source\include
  name: deprecated_definitions.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 1EA4EDD5EA90F43EC407DE32441159A9
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mz_w1_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: B1D1D455E111FA70C46AD40562D78CE2
  logicalPath: FreeRTOS\Source\include
  name: event_groups.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: B1D1D455E111FA70C46AD40562D78CE2
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mz_w1_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: FE17D325A06479D956285C5438994B83
  logicalPath: FreeRTOS\Source\include
  name: list.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: FE17D325A06479D956285C5438994B83
- generatedChecksum: DDE2C9D46642D120A0202AC851E1A777
  logicalPath: FreeRTOS\Source\include
  name: message_buffer.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: DDE2C9D46642D120A0202AC851E1A777
- generatedChecksum: 2D674B8B1FCF07504AF90FA5CE2F9A23
  logicalPath: FreeRTOS\Source\include
  name: mpu_prototypes.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 2D674B8B1FCF07504AF90FA5CE2F9A23
- generatedChecksum: 953D372D8F7991D4F86AD4ABD42AE4CE
  logicalPath: FreeRTOS\Source\include
  name: mpu_wrappers.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 953D372D8F7991D4F86AD4ABD42AE4CE
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config\pic32mz_w1_curiosity\osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 167A43EFF8A31441EBF85AC77958A30B
  logicalPath: config\pic32mz_w1_curiosity\osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 167A43EFF8A31441EBF85AC77958A30B
- generatedChecksum: 9D6F205ECFDB2028C5CF766B52B5B7B2
  logicalPath: config\pic32mz_w1_curiosity\osal
  name: osal_freertos.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D6F205ECFDB2028C5CF766B52B5B7B2
- generatedChecksum: 9238A3759A2C6748FE493370DE35B5E0
  logicalPath: config\pic32mz_w1_curiosity\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 9238A3759A2C6748FE493370DE35B5E0
- generatedChecksum: 2B5072810107E051495C4B6379DEDA4E
  logicalPath: config\pic32mz_w1_curiosity\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 2B5072810107E051495C4B6379DEDA4E
- generatedChecksum: D2736DBCC706554376BCA0F311BC0DE7
  logicalPath: config\pic32mz_w1_curiosity\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: D2736DBCC706554376BCA0F311BC0DE7
- generatedChecksum: D5B124F7B292B92BE6CA0A7BDFD6F62F
  logicalPath: config\pic32mz_w1_curiosity\peripheral\uart
  name: plib_uart1.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: D5B124F7B292B92BE6CA0A7BDFD6F62F
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config\pic32mz_w1_curiosity\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 5A686FF678CBFBB4A1FEB86B66DCEC98
  logicalPath: FreeRTOS\Source\include
  name: portable.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5A686FF678CBFBB4A1FEB86B66DCEC98
- generatedChecksum: 6E4E1E4FD0B92BD15236DAA237ABCCAB
  logicalPath: FreeRTOS\Source\portable\MPLAB\PIC32MZ
  name: portmacro.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\portable\MPLAB\PIC32MZ
  security: NON_SECURE
  type: HEADER
  userChecksum: 6E4E1E4FD0B92BD15236DAA237ABCCAB
- generatedChecksum: 696F66B2428CC530389C53B5FE617CE1
  logicalPath: FreeRTOS\Source\include
  name: projdefs.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 696F66B2428CC530389C53B5FE617CE1
- generatedChecksum: 6CB1FF8C27E6755C63D75369D1D7A37A
  logicalPath: FreeRTOS\Source\include
  name: queue.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 6CB1FF8C27E6755C63D75369D1D7A37A
- generatedChecksum: 9F1AE7D29D09ED8CC21F3DA08049FB79
  logicalPath: FreeRTOS\Source\include
  name: semphr.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 9F1AE7D29D09ED8CC21F3DA08049FB79
- generatedChecksum: D0D11C3D2D1BD585018AE271E1AC3B8F
  logicalPath: FreeRTOS\Source\include
  name: stack_macros.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: D0D11C3D2D1BD585018AE271E1AC3B8F
- generatedChecksum: 7C71A9D2BEF16AC21C17ED5C2452C263
  logicalPath: FreeRTOS\Source\include
  name: stream_buffer.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 7C71A9D2BEF16AC21C17ED5C2452C263
- generatedChecksum: 84B3224817BDD8B37961BB3B3441E134
  logicalPath: FreeRTOS\Source\include
  name: task.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 84B3224817BDD8B37961BB3B3441E134
- generatedChecksum: null
  logicalPath: ''
  name: task1.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task2.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task3.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task4.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: C8BB70E2423A57902E9FDC0C9EC81F8D
  logicalPath: FreeRTOS\Source\include
  name: timers.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: C8BB70E2423A57902E9FDC0C9EC81F8D
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\pic32mz_w1_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config\pic32mz_w1_curiosity
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 34C817709D3F54FE0AD5A90F33B4CB7C
  logicalPath: config\pic32mz_w1_curiosity
  name: p32MZ1025W104132.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 34C817709D3F54FE0AD5A90F33B4CB7C
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MZ;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;../src/packs/PIC32MZ1025W104132_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-assembler
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MZ;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mz_w1_curiosity;
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-preprocessor
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MZ;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mz_w1_curiosity;
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MZ;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;../src/packs/PIC32MZ1025W104132_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
